name: {{ .ProName }}
envs:
  dev:
    domain: dev-{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  qa:
    https: true
    domain: qa-{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  preview:
    https: true
    domain: preview-{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  production:
    https: true
    domain: {{ .Domain }}
    timeZone: { name: China, offset: 28800 }

