name: {{ .ProName }}
envs:
  dev:
    externalURL: http://dev-{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  qa:
    externalURL: https://qa-{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  preview:
    externalURL: https://preview-{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  production:
    externalURL: https://{{ .Domain }}
    timeZone: { name: China, offset: 28800 }

