defaults: &defaults
  timeZone: { name: China, offset: 28800 }
  # mailer://smtp.exmail.qq.com:587/?user=报警<alarm@{{ .Domain }}>&pass=123456
  mailer: "mailer://smtp.qq.com:25/?user=小美<xiaomei-go@qq.com>&pass=zjsbosjlhgugechh"
  keepers: [ "小美<xiaomei-go@qq.com>" ]

name: {{ .ProName }}
envs:
  dev:
    <<: *defaults
    externalURL: http://dev-{{ .Domain }}
    cookie:
      name: token
      domain: dev-{{ .Domain }}
      path: /
      maxAge: 1M # Y:年; M:月; D:天; h:时; m:分; s:秒
    secret: {{ genSecret }}
    keepers: [ ]
  test:
    <<: *defaults
    externalURL: http://localhost:3000
    secret: {{ genSecret }}
    keepers: [ ]
  ci:
    <<: *defaults
    externalURL: http://localhost:3000
    secret: {{ genSecret }}
  qa:
    <<: *defaults
    externalURL: https://qa-{{ .Domain }}
    cookie:
      name: token
      domain: qa-{{ .Domain }}
      path: /
      maxAge: 1M # Y:年; M:月; D:天; h:时; m:分; s:秒
    secret: {{ genSecret }}
  preview:
    <<: *defaults
    externalURL: https://preview-{{ .Domain }}
    cookie:
      name: token
      domain: preview-{{ .Domain }}
      path: /
      maxAge: 1M # Y:年; M:月; D:天; h:时; m:分; s:秒
    secret: {{ genSecret }}
  production:
    <<: *defaults
    externalURL: https://{{ .Domain }}
    cookie:
      name: token
      domain: {{ .Domain }}
      path: /
      maxAge: 1M # Y:年; M:月; D:天; h:时; m:分; s:秒
    secret: {{ genSecret }}

